apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:18
      env:
        - name: POSTGRES_USER
          value: "{{ .Values.env.POSTGRES_USER }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.env.POSTGRES_PASSWORD }}"
        - name: POSTGRES_DB
          value: "{{ .Values.env.POSTGRES_DB }}"
      ports:
        - containerPort: {{ .Values.env.POSTGRES_PORT }}

      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: {{ .Values.env.POSTGRES_PORT }}
      targetPort: {{ .Values.env.POSTGRES_PORT }}